kind: Service
apiVersion: v1
metadata:
  labels:
    app: xneme-toskaboiler
  name: xneme-toskaboiler
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: xneme-toskaboiler
